VM changes to run BMC

diff --git a/q-script/yifei-q b/q-script/yifei-q
--- a/q-script/yifei-q
+++ b/q-script/yifei-q
@@ -44,14 +44,29 @@ host() {
 	cmdline+=" console=ttyS0,115200"
 	cmdline+=" kgdboc=ttyS1,115200"
 
-	local net
-	if [ "$SSH" = "y" ]; then
-		net+=" -netdev user,id=virtual,hostfwd=tcp:127.0.0.1:52222-:22"
-	else
-		net+=" -netdev user,id=virtual"
-	fi
-	net+=" -device virtio-net-pci,netdev=virtual"
+TAP=tap100
 
+# clean up old tap
+sudo ip link del $TAP
+# create new tap
+if ! ip link show $TAP &> /dev/null; then
+    sudo ip tuntap add mode tap $TAP
+    sudo ip addr add 192.168.111.1/24 dev $TAP
+    sudo ip link set $TAP up
+    echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward >/dev/null
+    sudo iptables -t nat -A POSTROUTING -o bond1 -j MASQUERADE
+    sudo iptables -I FORWARD 1 -i $TAP -j ACCEPT
+    sudo iptables -I FORWARD 1 -o $TAP -m state --state RELATED,ESTABLISHED -j ACCEPT
+fi
+
+	local net
+	# if [ "$SSH" = "y" ]; then
+	# 	net+=" -netdev user,id=virtual,hostfwd=tcp:127.0.0.1:52222-:22"
+	# else
+	# 	net+=" -netdev user,id=virtual"
+	# fi
+	# net+=" -device virtio-net-pci,netdev=virtual"
+	net+=" -device virtio-net-pci,netdev=n0,mac=AA:FC:00:00:00:01 -netdev tap,id=n0,ifname=$TAP,script=no,downscript=no "
 	local opts
 	[ "$MODULES" = "y" ] && opts+=" -m"
 	[ "$SSH" = "y" ] && opts+=" -s"
